FROM node:24-alpine AS builder

ARG SERVICE
ARG PORT

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
COPY nx.json tsconfig.base.json tsconfig.json ./
COPY packages/ packages/

RUN npm ci --legacy-peer-deps

RUN npx nx build ${SERVICE}

WORKDIR /app/packages/${SERVICE}

EXPOSE ${PORT}

COPY packages/marketplace/docker-seed.js ./docker-seed.js

CMD ["node", "dist/main.js"]
